In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [20]:
# ex1

In [7]:
a = np.linspace(start=12, stop=24, num=12, endpoint=False)
a

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [ ]:
# ex2

In [9]:
a1 = a.reshape((2,6))
a1

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [10]:
a2 = a.reshape((6,2))
a2

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [11]:
a3 = a.reshape((4,3))
a3

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [12]:
a4 = a.reshape((3,4))
a4

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [13]:
a5 = a.reshape((12,1))
a5

array([[12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.]])

In [ ]:
# ex3

In [15]:
m1 = a.reshape((2,-1))
m1

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [16]:
m2 = a.reshape((6,-1))
m2

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [17]:
m3 = a.reshape((3,-1))
m3

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [18]:
m4 = a.reshape((-1,6))
m4

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [19]:
m5 = a.reshape((-1,2))
m5

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [24]:
# ex4
# да
# The NumPy ndarray class is used to represent both matrices and vectors. 
# A vector is an array with a single dimension (there’s no difference between
# row and column vectors), while a matrix refers to an array with two dimensions.
# numpy.og

In [25]:
# ex5

In [28]:
matrix = np.random.normal(0,1,(3,4))
matrix

array([[ 0.06701774,  0.04939671,  0.10897048,  0.74248469],
       [ 0.82723445, -1.17440257,  0.60176608, -0.5785241 ],
       [-1.11488224,  1.42634632,  0.50463078,  0.8449138 ]])

In [30]:
array = matrix.reshape(-1)
array

array([ 0.06701774,  0.04939671,  0.10897048,  0.74248469,  0.82723445,
       -1.17440257,  0.60176608, -0.5785241 , -1.11488224,  1.42634632,
        0.50463078,  0.8449138 ])

In [31]:
# ex6

In [36]:
a = np.arange(20, 0, -2, dtype=int)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [37]:
# ex7

In [39]:
b = np.arange(20, 1, -2, dtype=int).reshape(10,-1)
b

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

In [40]:
# ex8

In [46]:
a = np.zeros((2,2))
b = np.ones((3,2))
ab = np.concatenate((a,b))
ab

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# ex9

In [66]:
a = np.arange(0, 12, 1, dtype=int)
A = a.reshape((4,3))
At = A.transpose()
B = np.matmul(A,At)
B.shape

(4, 4)

In [67]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [69]:
determinant = np.linalg.det(B)
determinant

0.0

In [ ]:
# Requirements to have an Inverse
# The matrix must be square. 
# The determinant of the matrix must not be zero
# отсюда -- нет!!

In [ ]:
# ex10

In [75]:
np.random.seed(42)
s=np.random.choice(20,10)
s

array([ 6, 19, 14, 10,  7,  6, 18, 10, 10,  3])

In [ ]:
# ex11

In [86]:
c = np.random.randint(low=0, high=16, size=16, dtype=int)
c

array([14,  1,  9, 11,  1,  9, 13,  3, 13, 14, 15, 14,  7, 13,  6, 11])

In [ ]:
#ex12

In [87]:
C = c.reshape((4,4))
C.shape

(4, 4)

In [90]:
D = B + C*10
D

array([[145,  24, 113, 142],
       [ 24, 140, 216, 152],
       [153, 226, 299, 352],
       [102, 252, 272, 412]])

In [99]:
determinant_D = np.linalg.det(D)
rank = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)
D_inv

array([[-0.00485964, -0.01126315,  0.02095953, -0.01207691],
       [-0.02185568, -0.0155098 ,  0.0332448 , -0.01514848],
       [ 0.00831481,  0.01362626, -0.01104857,  0.00154661],
       [ 0.00908177,  0.00327905, -0.018229  ,  0.01366161]])

In [ ]:
# ex13

In [100]:
D_inv[D_inv >= 0 ] = 1
D_inv[D_inv < 0 ] = 0
D_inv

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 1.],
       [1., 1., 0., 1.]])

In [108]:
E = np.where(D_inv==1, B, C)
E

array([[ 14,   1,  23,  11],
       [  1,   9,  86,   3],
       [ 23,  86,  15, 212],
       [ 32, 122,   6, 302]])